[project]
name = "dispatcher-maker"
version = "0.2.0"
description = "Package used with app to send incident to dispatcher"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.2",
    "requests>=2.32.5",
]
